# Generated by Django 4.1.5 on 2023-01-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
