# Generated by Django 4.1.5 on 2023-01-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
